apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
  namespace: bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      greymatter.io/cluster: bookinfo-edge
  template:
    metadata:
      labels:
        greymatter.io/cluster: bookinfo-edge
    spec:
      containers:
        # - name: opa
        #   image: openpolicyagent/opa:0.46.1-envoy-rootless
        #   args: [
        #     "run",
        #     "--server",
        #     "--addr=localhost:8181",
        #     "--log-level=debug",
        #     "--diagnostic-addr=0.0.0.0:8282",
        #     "--set=plugins.envoy_ext_authz_grpc.addr=:9191",
        #     "--set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.allow",
        #     "--set=plugins.envoy_ext_authz_grpc.enable-reflection=true",
        #     "--set=decision_logs.console=true",
        #     "--ignore=.*",
        #     "/policy/policy.rego",
        #   ]
        #   resources:
        #     limits:
        #       cpu: 200m
        #       memory: 512Mi
        #     requests:
        #       cpu: 50m
        #       memory: 128Mi
        #   volumeMounts:
        #   - readOnly: true
        #     mountPath: /policy
        #     name: opa-policy
        - name: sidecar
          image: greymatter.jfrog.io/release-oci/greymatter-proxy:1.8.1
          imagePullPolicy: Always
          ports:
          - containerPort: 10809
            name: proxy
          env:
            - name: XDS_CLUSTER
              value: bookinfo-edge
            - name: ENVOY_ADMIN_LOG_PATH
              value: /dev/stdout
            - name: PROXY_DYNAMIC
              value: "true"
            - name: XDS_ZONE
              value: default-zone
            - name: XDS_HOST
              value: controlensemble.greymatter.svc.cluster.local
            - name: XDS_PORT
              value: "50000"
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # volumeMounts:
          #   - name: tls-certs
          #     mountPath: /etc/proxy/tls/sidecar
      volumes:
        # - name: tls-certs
        #   secret:
        #     defaultMode: 420
        #     secretName: greymatter-bookinfo-edge-certs
        # - name: opa-policy
        #   secret:
        #     secretName: opa-policy
      imagePullSecrets:
      - name: gm-docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: edge
  namespace: bookinfo
spec:
  ports:
  - name: ingress
    port: 10809
    protocol: TCP
    targetPort: 10809
  selector:
    greymatter.io/cluster: bookinfo-edge
  type: LoadBalancer

